### ISSUE TITLE
Error when compiling with g++ and mpicxx

### ISSUE THREAD

**Issue by Hassenky** [sanshar/Block#14]
modules/npdm/npdm_expectations.C:855:18: error: ‘class std::map<std::vector<int>, SpinAdapted::Wavefunction>’ has no member named ‘emplace’
modules/npdm/npdm_expectations.C: In member function ‘void SpinAdapted::Npdm::Npdm_expectations::store(SpinAdapted::Npdm::NpdmSpinOps_base&)’:
modules/npdm/npdm_expectations.C:899:14: error: ‘class std::map<std::vector<int>, SpinAdapted::Wavefunction>’ has no member named ‘emplace’
make: *** [modules/npdm/npdm_expectations.o] Error 1

**Comment by gkc1000** [comment]
Hi, are you using a C++11 compliant compiler? emplace is part of the C++11
standard library.

**Comment by Hassenky** [comment]
I am using gcc 4.7 so I guess It does not support C++11. But, when I use intel compiler (2015), the same error happened. It is so strange.

"modules/npdm/npdm_expectations.C(855): error: class "std::map<std::vector<MPI_Datatype={int}, std::allocator<MPI_Datatype={int}>>, SpinAdapted::Wavefunction, std::less<std::vector<MPI_Datatype={int}, std::allocator<MPI_Datatype={int}>>>, std::allocator<std::pair<const std::vector<MPI_Datatype={int}, std::allocator<MPI_Datatype={int}>>, SpinAdapted::Wavefunction>>>" has no member "emplace"
            waves_.emplace(spin,opw2);
                   ^

modules/npdm/npdm_expectations.C(899): error: class "std::map<std::vector<MPI_Datatype={int}, std::allocator<MPI_Datatype={int}>>, SpinAdapted::Wavefunction, std::less<std::vector<MPI_Datatype={int}, std::allocator<MPI_Datatype={int}>>>, std::allocator<std::pair<const std::vector<MPI_Datatype={int}, std::allocator<MPI_Datatype={int}>>, SpinAdapted::Wavefunction>>>" has no member "emplace"
        waves_.emplace(spin,opw2);
               ^

compilation aborted for modules/npdm/npdm_expectations.C (code 2)

**Comment by gkc1000** [comment]
Did you use -std=c++11

**Comment by gkc1000** [comment]
I noticed on the compiler webpage

https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler

   1. *1: * Full C++11 support requires gcc 4.8 environment or newer on
   Linux*

**Comment by junyang4711** [comment]
To be on safe side, please try g++ version higher than 4.8.2 with
-std=c++11.

Jun

**Comment by Hassenky** [comment]
With gcc 4.7, I did use -std=c++11, but could nod overcome "emplace" error. I'll install new version of gcc and try again. Thanks so much.

**Comment by junyang4711** [comment]
gcc 4.7 supports some but many features of c++11 for which you will
continually see more errors of compiling. Newer version shall solve the
problem.

Jun
