### ISSUE TITLE
mpirun meets a segmentation fault

### ISSUE THREAD

**Issue by diradical** [sanshar/Block#15]
error message:
> mpirun -np 2 ./block.spin_adapted input.dat > output.dat 
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: (nil)
[ 0] /lib64/libpthread.so.0(+0xf890)[0x2b3e55ef5890]
[ 1] ./block.spin_adapted[0x5528f6]
[ 2] ./block.spin_adapted[0x7d68a4]
[ 3] ./block.spin_adapted[0x7d0e88]
[ 4] ./block.spin_adapted[0x7cf3ab]
[ 5] ./block.spin_adapted[0x7ce3bd]
[ 6] ./block.spin_adapted[0x46d2bb]
[ 7] ./block.spin_adapted[0x46a453]
[ 8] ./block.spin_adapted[0x54d02a]
[ 9] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b3e57841b05]
[10] ./block.spin_adapted[0x427db7]
*** End of error message ***

it seems that the error occurs when a new thread is being created.
source code downloaded on 06-10-2015.
compiler: intel 2015 update 3
mpi version: openmpi-1.8.4
boost library version: 1.55.0

**Comment by gkc1000** [comment]
Please send the input file, also precise version that was used (e.g. where
was it downloaded from?)
If you are downloading from Github, please try again with the v1.0.0 tagged
release. (We do not support development snapshots).

**Comment by diradical** [comment]
maybe something wrong with intel compiler 2015 leads to the segmentation fault. ：-（
the program works fine when compiled with GCC 4.8. ：-|

**Comment by gkc1000** [comment]
Please send the input file still that leads to the problem so we can
reproduce it.

**Comment by diradical** [comment]
The input file is a test example included in the source package.
input.dat in README_EXAMPLE/1 and FCIDUMP in README_EXAMPLE.

> 在 2015年6月24日，18:44，gkc1000 <notifications@github.com> 写道：
> 
> Please send the input file still that leads to the problem so we can
> reproduce it.
>

**Comment by junyang4711** [comment]
Hi,
We couldn't reproduce your problem, as the same calculation was successful, using two CPUs in parallel, and Block 1.0.0 compiled with intel compiler 15.0.2. Please check how your libraries (boost, mpi, mkl...) are set up. They must be compatible with intel compiler. We recommend to use the same version of compiler for both Block and libraries.

**Comment by diradical** [comment]
I'm sure that openmpi 1.8.4, boost 1.55.0 and Block 1.0.0 were all compiled with intel compiler 15.0.3. However if using GCC 4.8.3 instead of icpc, the binary works perfect.
Anyway, thank you all for the code. :-)

**Comment by gkc1000** [comment]
We have not been able to reproduce the problem with icpc 15.0.2.  If this problem persists, please reopen the issue.
