### ISSUE TITLE
npdm_expectations.C

### ISSUE THREAD

**Issue by similt** [sanshar/Block#17]
Can you help to get rid of the error while compiling ?

modules/npdm/npdm_expectations.C(855): error: class "std::map<std::vector<int, std::allocator<int>>, SpinAdapted::Wavefunction, std::less<std::vector<int, std::allocator<int>>>, std::allocator<std::pair<const std::vector<int, std::allocator<int>>, SpinAdapted::Wavefunction>>>" has no member "emplace"
            waves_.emplace(spin,opw2);
                   ^

modules/npdm/npdm_expectations.C(899): error: class "std::map<std::vector<int, std::allocator<int>>, SpinAdapted::Wavefunction, std::less<std::vector<int, std::allocator<int>>>, std::allocator<std::pair<const std::vector<int, std::allocator<int>>, SpinAdapted::Wavefunction>>>" has no member "emplace"
        waves_.emplace(spin,opw2);
               ^

compilation aborted for modules/npdm/npdm_expectations.C (code 2)
make: *** [modules/npdm/npdm_expectations.o] Error 2

**Comment by shengg** [comment]
std::map::emplace is only implemented c++11. Changing c++ compiler, for
example using GCC 4.8, could solver the problem.

Best regards,

Sheng Guo
Ph.D student
351 Frick Laboratory
Department of Chemistry
Princeton University

**Comment by junyang4711** [comment]
Hi

Please keep it in mind that the instruction for compiling Block and
compiler requirement is given on github project page and also the following
online documentation:

http://sanshar.github.io/Block/
