### ISSUE TITLE
BLOCK runtime error

### ISSUE THREAD

**Issue by SebWouters** [sanshar/Block#18]
Hi,

I tried to compile BLOCK as noted on http://sanshar.github.io/Block/, which finally succeeded with boost 1.55.0 and the intel mpiicpc compiler version 15.0.1 20141023. Boost is compiled with the intel icpc compiler with the same version number. However, when I try to run block with intel's mpirun I get the following error message:

    Attempting to use an MPI routine before initializing MPI

Any ideas?

Best wishes,
Sebastian

**Comment by gkc1000** [comment]
Is this the 1.0 tagged release, or the github snapshot?

On Thu, Jul 16, 2015 at 6:12 PM, Sebastian Wouters <notifications@github.com

**Comment by SebWouters** [comment]
Sorry, forgot to mention: the v1.0.0 release

**Comment by gkc1000** [comment]
Can you try the github snapshot to see if this is a bug that was fixed
already?

On Thu, Jul 16, 2015 at 6:16 PM, Sebastian Wouters <notifications@github.com

**Comment by SebWouters** [comment]
With commit add65f3b2bda12b0f57f8c7a2cdb6c5965a6c5a8 it works fine:

testing energy for c2_d2h...
PASSED ....
PASSED ....
testing 2-pdm for c2_d2h...
PASSED ....
PASSED ....
performing energy test on h2o...
PASSED ....
performing reorder, 1-pdm test on hubbard...
PASSED ....
PASSED ....
performing nonspinadapted test on hubbard...
PASSED ....
PASSED ....
performing heisenberg test...
PASSED ....
performing bcs test...
PASSED ....
PASSED ....
PASSED ....
testing energy, 1- and 2-pdm for c2_d2h_smallM...
PASSED ....
PASSED ....
PASSED ....
PASSED ....
testing state specific excited states...
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
PASSED ....
testing dinfh irrep1 state...
PASSED ....
PASSED ....
testing dinfh irrep4 state...
PASSED ....
PASSED ....
testing dinfh irrep5 state...
PASSED ....
PASSED ....
testing C5v irrep1 state...
PASSED ....
PASSED ....

etcetera
