### ISSUE TITLE
How to define the active space in dmrg-nevpt2?

### ISSUE THREAD

**Issue by dingld** [sanshar/Block#19]
[Block-1.0.1] 
From the tests given in dmrg_tests directory,  no clue about the active space of dmrg-nevpt2 is found, nor can I find the dmrg-scf module. Is the latest version of Block able to conduct dmrg-scf calculations?  And I also would like to know if it is possible to delete certain virtual orbitals in dmrg-nevpt2 calculation in Block-input-file, which of course can be done by deleting by re-writing FCIDUMP-file.

**Comment by gkc1000** [comment]
DMRG-SCF is carried out by running Block together with other programs. For
example, you can run Block as a module in PySCF, which will then carry out
DMRG-SCF.

To remove certain virtual orbitals in NEVPT2 you would have to
truncate/rewrite the FCIDUMP file.

**Comment by dingld** [comment]
Thanks for the answer. 
About the definition of active-orbital-space of DMRG-NEVPT2,  I have noticed that the "Block/module/nevpt2/nevpt2.h" gives descrition.

**Comment by gkc1000** [comment]
There are several algorithms for running NEVPT2 with DMRG. What is called
"DMRG-NEVPT2" in the Block source code is a particular formulation that
remains under development. It is not yet for use. A more standard way is to
run NEVPT2 via PySCF which then computes the intermediates through Block.
This is possible for active spaces that are not too large (say about 22
orbitals). A 3rd option is to run an MPSPT2 calculation via Block.
Unfortunately, we have not yet had time to document these options
carefully, but will be doing so soon.

Note that using an active space is not the same as deleting virtuals.

**Comment by dingld** [comment]
I am afraid that 4-pdm could be still a bottleneck when running nevpt2 via PySCF.  By the way, may I know if the Block-1.0.1 constructs operators using matrix product representation in DMRG-NEVPT2 or MPSPT2?

**Comment by gkc1000** [comment]
Hi, any DMRG code internally uses a matrix product representation. MPSPT2
does not construct any pdm intermediates.
