### ISSUE TITLE
Dynamic correlation

### ISSUE THREAD

**Issue by huuco** [sanshar/Block#22]
Hi,

In order to obtain quantitative results, static correlation (which is nicely treated by DMRG) is not enough. We really need dynamic correlation included. I can see that several methods were implemented in Block to treat dynamic correlation, but none of them are well documented.
- NEVPT2: there is an example, but no instruction to prepare the input files.
- MPS-NEVPT2
- MPSPT2
- cu(4)-CASPT2 interfaced with Molcas. This seems promising, considering that Molcas is widely used. But there is neither an instruction nor even an example.

Thus it will be very nice if the authors can include some example as well as manual of these method.
Thank you.

**Comment by gkc1000** [comment]
Thanks for your comment. 

There are certainly many new features that we hope to be available for wide use in the near future. As you know, we provide this software as a service for the community. Documenting, cleaning things up, all take time, which has to be balanced with actually doing science, which is our main objective! For example, the papers relating to NEVPT2 and DMRG have not even been written yet. We expect that in an upcoming 1.1 release scheduled for the end of the year, we will release a version with significant speed and parallelization improvements to the core DMRG functions, as well as with more examples for the above methods. At the current time, the easiest way to use the above methods is to read the source, which is of course available on this site.

Note that if your system is not too large, e.g. <20 electrons, and <120 orbitals, DMRG can be used in a brute force way to include dynamic correlation without any additional effort.
