### ISSUE TITLE
mpspt2

### ISSUE THREAD

**Issue by lucamontana** [sanshar/Block#23]
Dear all, 

How is PERTURB file in Block/dmrg_tests/mpspt2/ obtained ?
Is BLOCK 1.1 going to be available ?

Best wishes
Luca

**Comment by gkc1000** [comment]
Hi Luca,

Block 1.1 has been released. NEVPT2 is now available and can be run for systems, using MPS compression, with about 30 orbitals, through the Block / PySCF interface. Please check the documentation for details and try it out!

Garnet

**Comment by gkc1000** [comment]
(It can be checked out on the 1.1-alpha tag, or as usual through the Princeton website).

**Comment by lucamontana** [comment]
Dear Garnet, 
many thanks, but how can i run a nevpt2 calculation using molpro ?I would like to start from molpro, as i am much more familiar with molpro.
Best wishesLuca

Date: Mon, 15 Feb 2016 05:39:58 -0800

**Comment by gkc1000** [comment]
Unfortunately, the NEVPT2 algorithm in Molpro is limited to small active spaces. Thus, to use DMRG with NEVPT2 it is necessary to use a different implementation of NEVPT2. This implementation is part of PySCF. Thus, it will not be possible to run DMRG + NEVPT2 through Molpro.

Try out PySCF - there are plenty of examples!

**Comment by lucamontana** [comment]
Dear Garnet, 

many thanks.
I compiled PySCF yesterday and i am going through tutorials. I see that there is also an implementation of NEVPT2 in BLOCK.  Since i compiled BLOCK with an older gcc compiler, i commented in the BLOCK code that part concerning NEVPT2,
to be able to compile the code. Hopefully this will cause no problem.


There is also mpspt2 module in BLOCK. Is is possible to use mpspt2 starting from molpro ?   

I was unable to find an example showing how to run drmg gradient calculation in excited states.

Bests
LUCA

Date: Mon, 15 Feb 2016 20:15:20 -0800

**Comment by gkc1000** [comment]
Hi Luca,
In principle, it should not be hard to implement MPSPT2 to interface Molpro. However, the MPSPT2 implementation is limited in the total number of orbitals it can treat, so we still recommend use of the regular NEVPT2 code supplied through PySCF's interface with Block.
